name: Build

on:
  push:
    branches:
      - feature/CI

jobs:
  build:
    name: Build App
    runs-on: macOS-latest
    env:
      THEOS: theos

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install Dependencies
      run: brew install ldid xz
    - name: Setup Theos
      uses: actions/checkout@master
      with:
        repository: theos/theos
        ref: 8771215f765e774bfefdacc6ddf0e151c2973d49
        path: theos
        submodules: recursive
    - name: Download SDK
      uses: actions/checkout@master
      with:
        repository: Itaybre/iPhoneOS13.3.sdk
        ref: 883201e5f94742401cb9a85bdaefd2c8ed3461ba
        path: theos/sdks/iPhoneOS13.3.sdk
    - name: Debug List Files
      run: |
        ls
        pwd
        cd $THEOS
        pwd
        ls
    - name: Build Package
      run: | 
        pwd
        echo $THEOS
        ls $THEOS
        ls $THEOS/makefiles
        make package
      env:
        THEOS: theos